# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='nid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='nid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='nid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
