# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0002_auto_20170630_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='nid',
            new_name='Eid',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='nid',
            new_name='Eid',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='nid',
            new_name='Eid',
        ),
        migrations.AddField(
            model_name='hod',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='position',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='position',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='position',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
