# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0007_auto_20170630_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='trainings',
        ),
        migrations.AddField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(to='msrh_user.Training'),
        ),
    ]
