# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0008_auto_20170630_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
    ]
