# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0009_auto_20170702_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='head_of_program',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='organised_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='topic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='venue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
