# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0010_auto_20170702_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='training',
            name='organised_by',
        ),
    ]
