# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0011_auto_20170702_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date',
        ),
    ]
