# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0012_remove_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
